version: '3.7'

services:
  image-service:
    image: image-service
    ports:
      - "8200:8200"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "image-service"
networks:
  backend:
    driver: bridge
